add social/creators/dictionary/userhandles API
insightiq-ai/iiq-managed-service pull request #2
Opened 2024-07-26 07:36 UTC by vasu-iiq

2024-07-29 05:46 UTC, kushal-o2 requested changes

2024-07-29 05:46 UTC, kushal-o2 commented on app/events/db/db_table_field_mappings.yaml
> +        unique_key: iiq_id
I think, iiq_id field does not come in response.

2024-07-29 05:46 UTC, kushal-o2 commented on app/events/db/db_table_field_mappings.yaml
> +                id: handle_id
I think, handle_id field does not come in response.

2024-07-29 09:36 UTC, kushal-o2 commented on app/events/db/migrations/db_table_sql_scripts.sql
> +    iiq_id         UUID                                 NOT NULL,
can you handle the columns here as well

2024-07-30 15:08 UTC, anujith-s approved these changes

2024-07-31 11:49 UTC, merged